---
title: "Diamond"
author: "Zhanhao Zhang"
date: "2/17/2020"
output: pdf_document
---

Required Packages:
```{r}
library(corrplot)
library(tidyverse)
library(data.table)
library(sets)
library(dequer)
library(MASS)
```

Load Data:
```{r}
diamond <- read.csv("diamonds.csv")
summary(diamond)
hist(diamond$carat, probability = T, main = "Histogram of Weight",
     xlab = "carat", breaks = 10)
```
Histograms:
```{r}
plot_histograms <- function(var = "all", num_plot_row = 2){
  plot_single_histogram <- function(single_var){
    if(is.numeric(diamond[[single_var]])){
      hist(diamond[[single_var]], 
                main = paste("Histogram of", single_var), xlab = single_var)
    } else{
      plot(diamond[[single_var]], xlab = single_var,
                main = paste("Histogram of", single_var))
    }
  }
  
  plot_multiple_histograms <- function(multiple_var){
    len <- length(multiple_var)
    if(ceiling(len / num_plot_row) > 3){
      par(mfrow = c(3, num_plot_row))
      for(i in 1:(3 * num_plot_row)){
        plot_single_histogram(multiple_var[i])
      }
      par(mfrow = c(1, 1))
      plot_multiple_histograms(multiple_var[(3 * num_plot_row + 1) : len])
    } else{
      n.rows <- ceiling(length(var) / num_plot_row)
      par(mfrow = c(n.rows, num_plot_row))
      for(i in 1:len){
        plot_single_histogram(multiple_var[i])
      }
      par(mfrow = c(1, 1))
    }
  }
  
  if(length(var) > 1){
    plot_multiple_histograms(var)
  } else if(var == "all"){
    plot_multiple_histograms(colnames(diamond)[2:ncol(diamond)])
  } else{
    plot_single_histogram(var)
  }
}

plot_histograms()
plot_histograms("carat")
plot_histograms(c("carat", "x", "y", "z"))
```

Correlation Matrices and Plots:
```{r}
plot_correlations <- function(var = "all"){
  if(length(var) > 1){
    df <- c()
    for(v in var){
      df <- cbind(df, as.numeric(diamond[[v]]))
    }
    colnames(df) <- var
    cor(df)
    corrplot(cor(df), method = "circle")
  } else if(var == "all"){
    plot_correlations(colnames(diamond)[2:ncol(diamond)])
  } else{
    stop("You should give at least 2 predictors!")
  }
}

plot_correlations()
```

Compress Data Frame:
```{r}
get_compressed_df <- function(dataframe, predictor_to_compress, 
                              compressed_vector, bin.width){
  df_new <- c()
  for(v in compressed_vector){
    tmp <- dataframe[dataframe[[predictor_to_compress]] <= v + bin.width & 
                       dataframe[[predictor_to_compress]] >= v - bin.width,]
    tmp[[predictor_to_compress]] <- v
    df_new <- rbind(data.frame(df_new), data.frame(tmp))
  }
  return(df_new)
}

compressed_df <- get_compressed_df(diamond, "carat", c(0.3, 0.5, 0.8, 1, 1.5), 0.03)
summary(compressed_df)
head(compressed_df)
```

Model Evaluation -- Assumptions on Residual:
```{r}
plot_residual_assumptions <- function(lm){
  par(mfrow = c(2, 2))
  plot(lm, which = 1)
  qqnorm(lm$residuals)
  qqline(lm$residuals, col = "red")
  plot(lm, which = 4)
  plot(lm, which = 5)
  par(mfrow = c(1, 1))
}
plot_residual_assumptions(lm(price ~ . - X, data = diamond))
```

Model Selection:
```{r}
## BFS
non_greedy_model_selection <- function(all_vector, response, init_vector = NULL,
                                       criteria = c("AIC", "BIC", "LOOCV"),
                                       n.best = 3, greedy = T, diamond = diamond){
  if(!criteria %in% c("AIC", "BIC", "LOOCV")){
    stop("criteria can only be AIC, BIC, LOOCV")
  }
  if(is.null(init_vector)){
    init_vector <- c()
  }
  get_model <- function(vec){
    if(length(vec) == 0){
      return(lm(as.formula(paste0(response, "~ 1")), data = diamond))
    }
    predictors <- paste(vec, collapse = "+")
    return(lm(as.formula(paste0(response, "~", predictors)), data = diamond))
  }
  compute_score <- function(lm){
    if(criteria == "AIC"){
      return(AIC(lm))
    } else if(criteria == "BIC"){
      return(BIC(lm))
    } else{
      return(mean((residuals(lm)/(1-hatvalues(lm)))^2))
    }
  }
  
  predictors_queue <- queue()
  score_queue <- queue()
  pushback(predictors_queue, init_vector)
  init.model <- get_model(init_vector)
  init.score <- compute_score(init.model)
  pushback(score_queue, init.score)
  best_models <- list(init_vector)
  for(i in 2:n.best){
    best_models[[i]] <- init_vector
  }
  best_scores <- rep(init.score, n.best)
  existing_vectors <- set(as.set(init_vector))
  j <- 0
  total <- 2^(length(all_vector) - length(init_vector))
  while(length(predictors_queue) > 0){
    j <- j + 1
    if(j %% 1 == 0){
      cat("\r", paste0("We have finished ", j, " trials out of up to ", 
                       total, " trials!"))
    }
    curr_vector <- pop(predictors_queue)
    curr_score <- pop(score_queue)
    additional_predictors <- all_vector[!all_vector %in% curr_vector]
    
    tmp_models <- NULL
    tmp_scores <- NULL
    i <- 0
    for(pred in additional_predictors){
      if(!set_contains_element(existing_vectors, as.set(c(curr_vector, pred)))){
        i <- i + 1
        model <- get_model(c(curr_vector, pred))
        score <- compute_score(model)
        existing_vectors <- set_union(existing_vectors, 
                                        set(as.set(c(curr_vector, pred))))
        if(score < curr_score){
          if(!greedy){
            pushback(predictors_queue, c(curr_vector, pred))
            pushback(score_queue, score)
          } else{
            tmp_models[[i]] <- c(curr_vector, pred)
            tmp_scores[i] <- score
          }
          if(score < max(best_scores)){
            idx <- which.max(best_scores)
            best_scores[idx] <- score
            best_models[[idx]] <- c(curr_vector, pred)
          }
        }
      }
    }
    if(greedy && !is.null(tmp_scores)){
      ord <- order(tmp_scores)
      for(i in 1:min(length(tmp_scores), n.best)){
        pushback(predictors_queue, tmp_models[[i]])
        pushback(score_queue, tmp_scores[i])
      }
    }
  }
  ordering <- order(best_scores)
  ret_scores <- c()
  ret_models <- c()
  for(o in ordering){
    ret_scores <- c(ret_scores, best_scores[o])
    ret_models <- c(ret_models, as.formula(paste0(response, "~", 
                                                  paste(best_models[[o]], 
                                                        collapse = "+"))))
    #ret_models <- c(ret_models, summary(get_model(best_models[[o]])))
  }
  return(list(best_models = ret_models, best_scores = ret_scores))
}
```

Model Selection:
```{r}
all_vector <- c(colnames(diamond)[!colnames(diamond) %in% c("X", "price")])
tmp <- c()
for(i in 1:(length(all_vector) - 1)){
  for(j in (i + 1):length(all_vector)){
    #tmp <- c(tmp, paste0(all_vector[i], "*", all_vector[j]))
  }
}
all_vector <- c(all_vector, tmp)


init_vector <- c("carat", "cut", "color", "clarity", "depth", "table", "x")
additional <- c("carat*cut", "carat*color", "carat*clarity", "cut*color",
                "cut*clarity", "color*clarity", "cut*depth", "carat*depth",
                "depth*table", "depth*x", "table*x", "carat*table", "carat*x")
non_greedy_model_selection(all_vector = c(init_vector, additional), response = "price", 
                           criteria = "LOOCV", n.best = 3, greedy = F,
                           init_vector = init_vector)
```

Anova Tests on Interaction Terms:
```{r}
test_interactions <- function(all_vector, data, level = 0.05, correction = NULL,
                              log = T){
  if(!is.null(correction) && !correction %in% c("Bonferroni", "Holm", "FDR")){
    stop("correction can only be NULL, Bonferroni, Holm, or FDR")
  }
  
  get_formula <- function(vec){
    if(length(vec) == 0){
      return(as.formula(paste0(response, "~ 1")))
    }
    predictors <- paste(vec, collapse = "+")
    return(as.formula(paste0(response, "~", predictors)))
  }
  
  complete_formula <- get_formula(all_vector)
  complete_model <- lm(complete_formula, data = data)
  
  interaction_predictors <- all_vector[grepl("\\*|:", all_vector, fixed = F)]
  pvalues <- c()
  for(pred in interaction_predictors){
    reduced_predictors <- interaction_predictors[interaction_predictors != pred]
    reduced_formula <- get_formula(reduced_predictors)
    reduced_model <- lm(reduced_formula, data = data)
    anv <- anova(reduced_model, complete_model)
    if(log){
      print(complete_formula)
      print(reduced_formula)
      print(paste("p-value is:", anv$`Pr(>F)`[2]))
      print("")
    }
    pvalues <- c(pvalues, anv$`Pr(>F)`[2])
  }
  
  significant_predictors <- c()
  len <- length(interaction_predictors)
  if(is.null(correction)){
    significant_predictors <- interaction_predictors[!is.na(pvalues) & pvalues < level]
  } else if(correction == "Bonferroni"){
    significant_predictors <- interaction_predictors[!is.na(pvalues) & 
                                                       pvalues < level / len]
  } else if(correction == "Holm"){
    p_orders <- order(pvalues)
    for(i in 1:len){
      if(!is.na(pvalues[p_orders[i]]) && pvalues[p_orders[i]] < level / (len + 1 - i)){
        significant_predictors <- c(significant_predictors,
                                    interaction_predictors[p_orders[i]])
      } else{
        break
      }
    }
  } else{
    p_orders <- order(pvalues)
    for(i in len:1){
      if(!is.na(pvalues[p_orders[i]]) && pvalues[p_orders[i]] < level / len * i){
        significant_predictors <- interaction_predictors[p_orders[1:i]]
        break
      }
    }
  }
  
  writeLines(paste("Significant interaction predictors are:\n", 
              paste(significant_predictors, collapse = ",")))
  return(significant_predictors)
}
```